### PR TITLE
manager/components/ moved to assets/components/

### PR DESCRIPTION
**Pull request by bertoost**
See issue
https://github.com/danyaPostfactum/modx-ace/issues/1

### CODE REVIEW

**Comment by bertoost** [comment]
And see https://github.com/danyaPostfactum/modx-ace/issues/4

**Comment by jpdevries** [comment]
Thanks for doing this. No extra should store files in the manager. Perfect scenario why not, I'm working on a 2.2.8 site, don't have phpmyadmin or SSH currently just manager access. I installed Ace, webserver doesn't allow manager folder to be modified, and the result is the entire Manager crashed and is now rendered useless.

**Comment by bertoost** [comment]
Exactly! As long MODX doesn't support a manager/components/ (or such) directory, components should not do that by theirself! This is working only on servers running something like suPHP or similar or when you can change the permissions of directories, but packages may not assume that.

Besides that; when you running the manager on different domain I understand the cross-domain issues, but MODX should support that in first place! ;-)

**Comment by jpdevries** [comment]
Ideally MODX also shouldn't completely choke on the connector that minifies assets if one of them doesn't exist or isn't readable

**Comment by jpdevries** [comment]
I ran this by the core team today and the response:
"ace tries to put things in the manager_path/assets/ which is not an officially supported location for component assets"

**Comment by christianseel** [comment]
+1 this PR

**Comment by danyaPostfactum** [comment]
Thanks @bertoost . I finally moved files :)
I cherry-picked your lexicon commit (https://github.com/danyaPostfactum/modx-ace/commit/6006fa326bd3be37ee269386e8bb08f82bb3276c)

**Pull request closed without merging**
