### PR TITLE
Fix using Ace for resources

### PR DESCRIPTION
**Pull request by Mark-H**

### CODE REVIEW

**Comment by danyaPostfactum** [comment]
Ace works with resources. Just set use_editor to false, or disable RTE for certain resource.
The rule is simple: you get Ace every time you have no RTE.

**Comment by Mark-H** [comment]
Ace is an editor.

If I set use_editor to yes, and which_editor to Ace, I expect any resource that is enabled to use an editor to use Ace. I can understand where you're coming from in that Ace is not a rich text editor but a code editor, but say I inherit a site that's been using tinymce and I want finer control over the markup cause the client screwed things up - I switch the editor to Ace and start cleaning things up. I don't want to disable use_editor, cause I still want an editor: Ace. 

It is very counter intuitive to have to disable editors or richtext on all resources in order to see this editor.

**Comment by danyaPostfactum** [comment]
The current implementation allows to use both code and rte editors. Personally I like this feature. I and some of my clients use both editors ( RTE is good if not to misuse it). Also, description of `use_editor` setting tells about RTE, not source editor. Also, `richtext` checkbox of resource definitely means RTE. And I don't see any reason to use a plain textarea (by disabling `use_editor` or `richtext` checkbox) when a source editor is available.

Of course, this behavior is not expected for someone, but this is quite reasonable and useful.

**Comment by danyaPostfactum** [comment]
And yes, I would like to add the Ace into the CKEditor. By the way, CodeMirror plugin for CKEditor [already exists](http://ckeditor.com/addon/codemirror).

**Comment by danyaPostfactum** [comment]
Thanks for the discussion. I'm closing this since current implementation is flexible enough and works fine (as far as I know).

**Pull request closed without merging**
